[general]
api_token={{ OPNsense.pushover.general.APIToken|default("")|replace("\n", "")|replace("\r", "") }}
user_key={{ OPNsense.pushover.general.UserKey|default("")|replace("\n", "")|replace("\r", "") }}
device={{ OPNsense.pushover.general.Device|default("")|replace("\n", "")|replace("\r", "") }}
priority={{ OPNsense.pushover.general.Priority|default("normal")|replace("\n", "")|replace("\r", "") }}
sound={{ OPNsense.pushover.general.Sound|default("")|replace("\n", "")|replace("\r", "") }}
notify_gateway={{ OPNsense.pushover.general.NotifyGateway|default("0") }}
notify_gateway_threshold={{ OPNsense.pushover.general.NotifyGatewayThreshold|default("0") }}
notify_reboot={{ OPNsense.pushover.general.NotifyReboot|default("0") }}
notify_config={{ OPNsense.pushover.general.NotifyConfig|default("0") }}
enabled={{ OPNsense.pushover.general.Enabled|default("0") }}
notify_ups={{ OPNsense.pushover.general.NotifyUPS|default("0") }}
notify_unbound={{ OPNsense.pushover.general.NotifyUnbound|default("0") }}
notify_dhcp={{ OPNsense.pushover.general.NotifyDHCP|default("0") }}
notify_dhcp6={{ OPNsense.pushover.general.NotifyDHCP6|default("0") }}
notify_firmware={{ OPNsense.pushover.general.NotifyFirmware|default("0") }}
notify_fan={{ OPNsense.pushover.general.NotifyFan|default("0") }}
fan_threshold={{ OPNsense.pushover.general.FanThreshold|default("30") }}
notify_cpu_temp={{ OPNsense.pushover.general.NotifyCPUTemp|default("0") }}
cpu_temp_threshold={{ OPNsense.pushover.general.CPUTempThreshold|default("80") }}
notify_openvpn={{ OPNsense.pushover.general.NotifyOpenVPN|default("0") }}
ovpn_threshold={{ OPNsense.pushover.general.OpenVPNThreshold|default("60") }}
notify_wireguard={{ OPNsense.pushover.general.NotifyWireGuard|default("0") }}
wg_threshold={{ OPNsense.pushover.general.WireGuardThreshold|default("300") }}
