#!/bin/sh

CONF=/usr/local/etc/pushover/pushover.conf

[ -f "$CONF" ] || exit 0

enabled=$(grep -m1 '^enabled' "$CONF" | cut -d= -f2 | tr -d ' ')
notify_reboot=$(grep -m1 '^notify_reboot' "$CONF" | cut -d= -f2 | tr -d ' ')

if [ "$enabled" = "1" ]; then
    /usr/sbin/service pushover onestart
fi

# Send boot notification (non-blocking; retries until route to Pushover API is up)
[ "$notify_reboot" = "1" ] || exit 0
(
    i=0
    while [ $i -lt 12 ]; do
        if /sbin/ping -c1 -t3 -q api.pushover.net >/dev/null 2>&1; then
            break
        fi
        sleep 5
        i=$((i + 1))
    done
    hostname=$(hostname -s)
    msg=$(printf 'System booted: %s' "$hostname" | /usr/local/bin/python3 -c "import urllib.parse,sys; print(urllib.parse.quote(sys.stdin.read()))")
    /usr/local/bin/python3 /usr/local/opnsense/scripts/OPNsense/Pushover/sendNotification.py \
        "$msg" 2>&1 | logger -t pushover -p daemon.notice
) &
