[notify]
command:/usr/local/bin/python3 /usr/local/opnsense/scripts/OPNsense/Pushover/sendNotification.py
parameters:%s
type:script_output
message:pushover send notification
errors:no

[start]
command:/usr/sbin/service pushover onestart
type:script
message:starting pushover service
errors:no

[stop]
command:/usr/sbin/service pushover onestop
type:script
message:stopping pushover service
errors:no

[restart]
command:/usr/sbin/service pushover onerestart
type:script
message:restarting pushover service
errors:no

[status]
command:/usr/sbin/service pushover onestatus
type:script_output
message:pushover service status
errors:no
